name: Deploy Portfolio

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # This step clones your repository

    - name: Set Up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install Dependencies
      run: yarn

    - name: Install Gatsby CLI
      run: npm install -g gatsby-cli

    - name: Install Project Dependencies
      run: nvm install

    - name: Build Gatsby Project
      run: gatsby build

    - name: Deploy to GitHub Pages
      run: npm run deploy

