name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # This step clones your repository
      
    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: |
        npm install -g yarn
        yarn
        npm install -g gatsby-cli

    - name: Build Gatsby Project
      run: npm run build
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

    # - name: Deploy to GitHub Pages
    #   env:
    #     GH_TOKEN: ${{ secrets.GH_TOKEN }} 
    # run: npm run deploy
